<?php
namespace frontend\widgets;

use backend\models\GoodsCategory;

use Codeception\Module\Redis;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
//        $redis = new \Redis();
//        $redis->connect('127.0.0.1', 6379, 2.5);
//        $category_html = $redis->get('category_html');
//        if($category_html == null){
            $categorys = GoodsCategory::findAll(['parent_id'=>0]);
            //将分类数据追加到分类视图文件
            $category_html = $this->renderFile('@app/widgets/view/category.php',['categorys'=>$categorys]);
//            $redis->set('category_html',$category_html);
//        }
        //返回html 用于输出
    return $category_html;
    }
}