<?php
namespace frontend\widgets;

use yii\base\Widget;
use yii\helpers\Url;

class SearchWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $html = <<<HTML
<div class="search fl">
            <div class="search_form" >
                <div class="form_left fl"></div>
                <form  name="serarch"  class="fl" method="get" action="list.html">
                    <input type="text" class="txt" value="请输入商品关键字" name="keywords" /><input type="submit" class="btn" value="搜索" />
                </form>
                <div class="form_right fl"></div>
            </div>
HTML;

        return $html;

    }
}